package com.remodex.mobile.ui.parity

import com.remodex.mobile.model.CODEX_PAIRING_QR_VERSION
import com.remodex.mobile.model.CODEX_SECURE_CLOCK_SKEW_TOLERANCE_MILLIS
import com.remodex.mobile.service.PairingPayload
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.intOrNull
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.longOrNull

private const val BRIDGE_UPDATE_COMMAND = "npm install -g remodex@latest"

sealed interface QrScannerPairingValidationResult {
    data class Success(val payload: PairingPayload) : QrScannerPairingValidationResult
    data class ScanError(val message: String) : QrScannerPairingValidationResult
    data class BridgeUpdateRequired(val prompt: BridgeUpdatePrompt) : QrScannerPairingValidationResult
}

data class BridgeUpdatePrompt(
    val title: String,
    val message: String,
    val command: String
)

fun validatePairingQrCode(
    code: String,
    nowMillis: Long = System.currentTimeMillis()
): QrScannerPairingValidationResult {
    val normalizedCode = code.trim()
    val jsonElement = runCatching { Json.parseToJsonElement(normalizedCode) }.getOrNull()
        ?: return QrScannerPairingValidationResult.ScanError(
            "Not a valid secure pairing code. Make sure you're scanning a QR from the latest Remodex bridge."
        )

    val payloadObject = runCatching { jsonElement.jsonObject }.getOrNull()
        ?: return QrScannerPairingValidationResult.ScanError(
            "Not a valid secure pairing code. Make sure you're scanning a QR from the latest Remodex bridge."
        )

    val qrVersion = payloadObject.int("v")
    if (qrVersion != null && qrVersion != CODEX_PAIRING_QR_VERSION) {
        return QrScannerPairingValidationResult.BridgeUpdateRequired(
            bridgeUpdatePrompt(
                message = "This QR code was generated by a different Remodex npm version. " +
                    "Update the package on your Mac to the latest release before scanning a new QR code."
            )
        )
    }

    if (qrVersion == null && looksLikeRemodexPairingPayload(payloadObject)) {
        return QrScannerPairingValidationResult.BridgeUpdateRequired(
            bridgeUpdatePrompt(
                message = "This QR code looks like it came from an older Remodex bridge. " +
                    "Update the npm package on your Mac to the latest release before scanning a new QR code."
            )
        )
    }

    val relayUrl = payloadObject.string("relay")
    if (relayUrl.isBlank()) {
        return QrScannerPairingValidationResult.ScanError(
            "QR code is missing the relay URL. Re-generate the code from the bridge."
        )
    }

    val sessionId = payloadObject.string("sessionId")
    if (sessionId.isBlank()) {
        return QrScannerPairingValidationResult.ScanError(
            "QR code is missing the session ID. Re-generate the code from the bridge."
        )
    }

    val macDeviceId = payloadObject.string("macDeviceId")
    if (macDeviceId.isBlank()) {
        return QrScannerPairingValidationResult.ScanError(
            "QR code is missing the Mac device ID. Re-generate the code from the bridge."
        )
    }

    val macIdentityPublicKey = payloadObject.string("macIdentityPublicKey")
    if (macIdentityPublicKey.isBlank()) {
        return QrScannerPairingValidationResult.ScanError(
            "QR code is missing the Mac identity key. Re-generate the code from the bridge."
        )
    }

    val expiresAt = payloadObject.long("expiresAt")
    if (expiresAt == null) {
        return QrScannerPairingValidationResult.ScanError(
            "QR code is missing expiry metadata. Re-generate the code from the bridge."
        )
    }

    if (expiresAt + CODEX_SECURE_CLOCK_SKEW_TOLERANCE_MILLIS < nowMillis) {
        return QrScannerPairingValidationResult.ScanError(
            "This pairing QR code has expired. Generate a new one from the Mac bridge."
        )
    }

    return QrScannerPairingValidationResult.Success(
        PairingPayload(
            sessionId = sessionId.trim(),
            relayUrl = relayUrl.trim(),
            macDeviceId = macDeviceId.trim(),
            macIdentityPublicKey = macIdentityPublicKey.trim(),
            expiresAt = expiresAt
        )
    )
}

private fun bridgeUpdatePrompt(message: String): BridgeUpdatePrompt {
    return BridgeUpdatePrompt(
        title = "Update Remodex on your Mac before scanning",
        message = message,
        command = BRIDGE_UPDATE_COMMAND
    )
}

private fun looksLikeRemodexPairingPayload(payloadObject: JsonObject): Boolean {
    val pairingKeys = setOf(
        "relay",
        "sessionId",
        "macDeviceId",
        "macIdentityPublicKey",
        "expiresAt",
        "v"
    )
    return payloadObject.keys.any { it in pairingKeys }
}

private fun JsonObject.string(key: String): String {
    return (this[key] as? JsonPrimitive)?.contentOrNull.orEmpty()
}

private fun JsonObject.long(key: String): Long? {
    return (this[key] as? JsonPrimitive)?.longOrNull
}

private fun JsonObject.int(key: String): Int? {
    return (this[key] as? JsonPrimitive)?.intOrNull
}
